version: '3'
services:
  bancoNgCash:
    image: postgres
    container_name: bancoNgCash
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - volume_bancoNgCash:/var/lib/postgresql/data

  desafio_trybe_back_node:
    build: .
    container_name: desafio_trybe_back_node
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://bancoNgCash:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run start:dev"
    depends_on:
      - bancoNgCash

volumes:
  volume_bancoNgCash: